/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminResult = { 'ok' : null } |
  { 'notAuthorized' : null } |
  { 'alreadyExists' : null } |
  { 'notFound' : null } |
  { 'notAdmin' : null };
export interface ArticleCard {
  'id' : ArticleId,
  'title' : string,
  'isPublished' : boolean,
  'isPremium' : boolean,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'coverImage' : [] | [ExternalBlob],
  'updatedAt' : Timestamp,
  'excerpt' : string,
  'category' : string,
  'authorPrincipal' : UserId,
}
export interface ArticleFull {
  'id' : ArticleId,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'isPremium' : boolean,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'coverImage' : [] | [ExternalBlob],
  'updatedAt' : Timestamp,
  'excerpt' : string,
  'category' : string,
  'authorPrincipal' : UserId,
}
export type ArticleId = bigint;
export interface ArticleInput {
  'title' : string,
  'content' : string,
  'isPremium' : boolean,
  'tags' : Array<string>,
  'coverImage' : [] | [ExternalBlob],
  'excerpt' : string,
  'category' : string,
}
export type ExternalBlob = Uint8Array;
export type InviteResult = { 'ok' : null } |
  { 'notAuthorized' : null } |
  { 'alreadyExists' : null } |
  { 'notFound' : null } |
  { 'alreadyBound' : null };
export interface InvitedUser {
  'boundPrincipal' : [] | [Principal],
  'email' : string,
  'addedAt' : Timestamp,
  'intendedRole' : Role,
  'boundAt' : [] | [Timestamp],
}
export interface PaymentRequest {
  'id' : PaymentRequestId,
  'status' : PaymentStatus,
  'expiresAt' : bigint,
  'userId' : Principal,
  'ownerPrincipal' : string,
  'createdAt' : bigint,
  'subaccount' : Uint8Array,
  'paymentType' : PaymentType,
  'amountE8s' : bigint,
}
export type PaymentRequestId = bigint;
export type PaymentStatus = { 'Consumed' : null } |
  { 'Verified' : null } |
  { 'Expired' : null } |
  { 'Pending' : null };
export type PaymentType = { 'ArticleUnlock' : ArticleId } |
  { 'Subscription' : null };
export type Role = { 'admin' : null } |
  { 'editor' : null } |
  { 'superadmin' : null };
export type SettingsResult = { 'ok' : null } |
  { 'notAuthorized' : null };
export interface SiteSettings { 'logoUrl' : [] | [string] }
export interface Subscription {
  'startTime' : Timestamp,
  'userId' : UserId,
  'expiryTime' : Timestamp,
}
export type Timestamp = bigint;
export interface UserAccess {
  'subscription' : [] | [Subscription],
  'isSubscribed' : boolean,
  'unlockedArticleIds' : Array<ArticleId>,
}
export type UserId = Principal;
export interface UserRole { 'principal' : UserId, 'role' : Role }
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAdmin' : ActorMethod<[UserId], AdminResult>,
  'addInvite' : ActorMethod<[string, Role], InviteResult>,
  'bindInvitePrincipal' : ActorMethod<[string], InviteResult>,
  'createArticle' : ActorMethod<[ArticleInput], ArticleCard>,
  'createPaymentRequest' : ActorMethod<[PaymentType], PaymentRequest>,
  'deleteArticle' : ActorMethod<[ArticleId], AdminResult>,
  'getAllArticlesAdmin' : ActorMethod<[], Array<ArticleCard>>,
  'getArticle' : ActorMethod<[ArticleId], [] | [ArticleFull]>,
  'getArticleCard' : ActorMethod<[ArticleId], [] | [ArticleCard]>,
  'getInviteByEmail' : ActorMethod<[string], [] | [InvitedUser]>,
  'getLogoUrl' : ActorMethod<[], [] | [string]>,
  'getMyPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getPublishedArticles' : ActorMethod<[], Array<ArticleCard>>,
  'getSettings' : ActorMethod<[], SiteSettings>,
  'getUserAccess' : ActorMethod<[], UserAccess>,
  'hasSuperadmin' : ActorMethod<[], boolean>,
  'initSuperadmin' : ActorMethod<[], AdminResult>,
  'isAuthorized' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<UserId>>,
  'listInvites' : ActorMethod<[], Array<InvitedUser>>,
  'listTrackedPrincipals' : ActorMethod<[], Array<UserId>>,
  'listUserRoles' : ActorMethod<[], Array<UserRole>>,
  'publishArticle' : ActorMethod<[ArticleId], AdminResult>,
  'removeAdmin' : ActorMethod<[UserId], AdminResult>,
  'removeInvite' : ActorMethod<[string], InviteResult>,
  'removeUserRole' : ActorMethod<[UserId], AdminResult>,
  'setUserRole' : ActorMethod<[UserId, Role], AdminResult>,
  'unpublishArticle' : ActorMethod<[ArticleId], AdminResult>,
  'updateArticle' : ActorMethod<[ArticleId, ArticleInput], AdminResult>,
  'updateSettings' : ActorMethod<[SiteSettings], SettingsResult>,
  'verifyPaymentRequest' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];