/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ArticleFull {
    id: ArticleId;
    title: string;
    content: string;
    isPublished: boolean;
    isPremium: boolean;
    createdAt: Timestamp;
    tags: Array<string>;
    coverImage?: ExternalBlob;
    updatedAt: Timestamp;
    excerpt: string;
    category: string;
    authorPrincipal: UserId;
}
export interface ArticleCard {
    id: ArticleId;
    title: string;
    isPublished: boolean;
    isPremium: boolean;
    createdAt: Timestamp;
    tags: Array<string>;
    coverImage?: ExternalBlob;
    updatedAt: Timestamp;
    excerpt: string;
    category: string;
    authorPrincipal: UserId;
}
export type Timestamp = bigint;
export interface UserAccess {
    subscription?: Subscription;
    isSubscribed: boolean;
    unlockedArticleIds: Array<ArticleId>;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserRole {
    principal: UserId;
    role: Role;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type PaymentType = {
    __kind__: "ArticleUnlock";
    ArticleUnlock: ArticleId;
} | {
    __kind__: "Subscription";
    Subscription: null;
};
export type ArticleId = bigint;
export interface Subscription {
    startTime: Timestamp;
    userId: UserId;
    expiryTime: Timestamp;
}
export type UserId = Principal;
export interface SiteSettings {
    logoUrl?: string;
}
export type PaymentRequestId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface InvitedUser {
    boundPrincipal?: Principal;
    email: string;
    addedAt: Timestamp;
    intendedRole: Role;
    boundAt?: Timestamp;
}
export interface PaymentRequest {
    id: PaymentRequestId;
    status: PaymentStatus;
    expiresAt: bigint;
    userId: Principal;
    ownerPrincipal: string;
    createdAt: bigint;
    subaccount: Uint8Array;
    paymentType: PaymentType;
    amountE8s: bigint;
}
export interface ArticleInput {
    title: string;
    content: string;
    isPremium: boolean;
    tags: Array<string>;
    coverImage?: ExternalBlob;
    excerpt: string;
    category: string;
}
export enum AdminResult {
    ok = "ok",
    notAuthorized = "notAuthorized",
    alreadyExists = "alreadyExists",
    notFound = "notFound",
    notAdmin = "notAdmin"
}
export enum InviteResult {
    ok = "ok",
    notAuthorized = "notAuthorized",
    alreadyExists = "alreadyExists",
    notFound = "notFound",
    alreadyBound = "alreadyBound"
}
export enum PaymentStatus {
    Consumed = "Consumed",
    Verified = "Verified",
    Expired = "Expired",
    Pending = "Pending"
}
export enum Role {
    admin = "admin",
    editor = "editor",
    superadmin = "superadmin"
}
export enum SettingsResult {
    ok = "ok",
    notAuthorized = "notAuthorized"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addAdmin(newAdmin: UserId): Promise<AdminResult>;
    addInvite(email: string, role: Role): Promise<InviteResult>;
    bindInvitePrincipal(email: string): Promise<InviteResult>;
    createArticle(input: ArticleInput): Promise<ArticleCard>;
    createPaymentRequest(paymentType: PaymentType): Promise<PaymentRequest>;
    deleteArticle(id: ArticleId): Promise<AdminResult>;
    getAllArticlesAdmin(): Promise<Array<ArticleCard>>;
    getArticle(id: ArticleId): Promise<ArticleFull | null>;
    getArticleCard(id: ArticleId): Promise<ArticleCard | null>;
    getInviteByEmail(email: string): Promise<InvitedUser | null>;
    getLogoUrl(): Promise<string | null>;
    getMyPaymentRequests(): Promise<Array<PaymentRequest>>;
    getMyRole(): Promise<Role | null>;
    getPublishedArticles(): Promise<Array<ArticleCard>>;
    getSettings(): Promise<SiteSettings>;
    getUserAccess(): Promise<UserAccess>;
    getLinkedWallet(): Promise<any | null>;
    linkWallet(walletPrincipal: any): Promise<{ ok: null } | { err: string }>;
    hasSuperadmin(): Promise<boolean>;
    initSuperadmin(): Promise<AdminResult>;
    isAuthorized(): Promise<boolean>;
    listAdmins(): Promise<Array<UserId>>;
    listInvites(): Promise<Array<InvitedUser>>;
    listTrackedPrincipals(): Promise<Array<UserId>>;
    listUserRoles(): Promise<Array<UserRole>>;
    publishArticle(id: ArticleId): Promise<AdminResult>;
    removeAdmin(target: UserId): Promise<AdminResult>;
    removeInvite(email: string): Promise<InviteResult>;
    removeUserRole(target: UserId): Promise<AdminResult>;
    setUserRole(target: UserId, role: Role): Promise<AdminResult>;
    unpublishArticle(id: ArticleId): Promise<AdminResult>;
    updateArticle(id: ArticleId, input: ArticleInput): Promise<AdminResult>;
    updateSettings(updated: SiteSettings): Promise<SettingsResult>;
    verifyPaymentRequest(reqId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AdminResult as _AdminResult, ArticleCard as _ArticleCard, ArticleFull as _ArticleFull, ArticleId as _ArticleId, ArticleInput as _ArticleInput, ExternalBlob as _ExternalBlob, InviteResult as _InviteResult, InvitedUser as _InvitedUser, PaymentRequest as _PaymentRequest, PaymentRequestId as _PaymentRequestId, PaymentStatus as _PaymentStatus, PaymentType as _PaymentType, Role as _Role, SettingsResult as _SettingsResult, SiteSettings as _SiteSettings, Subscription as _Subscription, Timestamp as _Timestamp, UserAccess as _UserAccess, UserId as _UserId, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAdmin(arg0: UserId): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addInvite(arg0: string, arg1: Role): Promise<InviteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvite(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_InviteResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvite(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_InviteResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async bindInvitePrincipal(arg0: string): Promise<InviteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.bindInvitePrincipal(arg0);
                return from_candid_InviteResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bindInvitePrincipal(arg0);
            return from_candid_InviteResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createArticle(arg0: ArticleInput): Promise<ArticleCard> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(await to_candid_ArticleInput_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ArticleCard_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(await to_candid_ArticleInput_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ArticleCard_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPaymentRequest(arg0: PaymentType): Promise<PaymentRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createPaymentRequest(to_candid_PaymentType_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PaymentRequest_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPaymentRequest(to_candid_PaymentType_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PaymentRequest_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteArticle(arg0: ArticleId): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllArticlesAdmin(): Promise<Array<ArticleCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticlesAdmin();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticlesAdmin();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticle(arg0: ArticleId): Promise<ArticleFull | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleCard(arg0: ArticleId): Promise<ArticleCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleCard(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleCard(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInviteByEmail(arg0: string): Promise<InvitedUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteByEmail(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteByEmail(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogoUrl(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoUrl();
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoUrl();
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPaymentRequests(): Promise<Array<PaymentRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPaymentRequests();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPaymentRequests();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<Role | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedArticles(): Promise<Array<ArticleCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedArticles();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedArticles();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<SiteSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_SiteSettings_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_SiteSettings_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserAccess(): Promise<UserAccess> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserAccess();
                return from_candid_UserAccess_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserAccess();
            return from_candid_UserAccess_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasSuperadmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasSuperadmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasSuperadmin();
            return result;
        }
    }
    async initSuperadmin(): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.initSuperadmin();
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSuperadmin();
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAuthorized(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAuthorized();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAuthorized();
            return result;
        }
    }
    async listAdmins(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdmins();
            return result;
        }
    }
    async listInvites(): Promise<Array<InvitedUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvites();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvites();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTrackedPrincipals(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrackedPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrackedPrincipals();
            return result;
        }
    }
    async listUserRoles(): Promise<Array<UserRole>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUserRoles();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUserRoles();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishArticle(arg0: ArticleId): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.publishArticle(arg0);
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishArticle(arg0);
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAdmin(arg0: UserId): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeInvite(arg0: string): Promise<InviteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeInvite(arg0);
                return from_candid_InviteResult_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeInvite(arg0);
            return from_candid_InviteResult_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeUserRole(arg0: UserId): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUserRole(arg0);
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUserRole(arg0);
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: UserId, arg1: Role): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishArticle(arg0: ArticleId): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishArticle(arg0);
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishArticle(arg0);
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArticle(arg0: ArticleId, arg1: ArticleInput): Promise<AdminResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, await to_candid_ArticleInput_n14(this._uploadFile, this._downloadFile, arg1));
                return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, await to_candid_ArticleInput_n14(this._uploadFile, this._downloadFile, arg1));
            return from_candid_AdminResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSettings(arg0: SiteSettings): Promise<SettingsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_SiteSettings_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_SettingsResult_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_SiteSettings_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_SettingsResult_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyPaymentRequest(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPaymentRequest(arg0);
                return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPaymentRequest(arg0);
            return from_candid_variant_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async linkWallet(walletPrincipal: any): Promise<{ ok: null } | { err: string }> {
        const result = await (this.actor as any).linkWallet(walletPrincipal);
        return result;
    }
    async getLinkedWallet(): Promise<any | null> {
        const result = await (this.actor as any).getLinkedWallet();
        if (Array.isArray(result) && result.length === 0) return null;
        if (Array.isArray(result) && result.length === 1) return result[0];
        return result;
    }
}
function from_candid_AdminResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminResult): AdminResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_ArticleCard_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleCard): Promise<ArticleCard> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ArticleFull_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArticleFull): Promise<ArticleFull> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_InviteResult_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InviteResult): InviteResult {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_InvitedUser_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvitedUser): InvitedUser {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRequest_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRequest): PaymentRequest {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentType): PaymentType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SettingsResult_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SettingsResult): SettingsResult {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_SiteSettings_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SiteSettings): SiteSettings {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserAccess_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserAccess): UserAccess {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ArticleFull]): Promise<ArticleFull | null> {
    return value.length === 0 ? null : await from_candid_ArticleFull_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ArticleCard]): Promise<ArticleCard | null> {
    return value.length === 0 ? null : await from_candid_ArticleCard_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvitedUser]): InvitedUser | null {
    return value.length === 0 ? null : from_candid_InvitedUser_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Role]): Role | null {
    return value.length === 0 ? null : from_candid_Role_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ArticleId;
    title: string;
    isPublished: boolean;
    isPremium: boolean;
    createdAt: _Timestamp;
    tags: Array<string>;
    coverImage: [] | [_ExternalBlob];
    updatedAt: _Timestamp;
    excerpt: string;
    category: string;
    authorPrincipal: _UserId;
}): Promise<{
    id: ArticleId;
    title: string;
    isPublished: boolean;
    isPremium: boolean;
    createdAt: Timestamp;
    tags: Array<string>;
    coverImage?: ExternalBlob;
    updatedAt: Timestamp;
    excerpt: string;
    category: string;
    authorPrincipal: UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        isPremium: value.isPremium,
        createdAt: value.createdAt,
        tags: value.tags,
        coverImage: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.coverImage)),
        updatedAt: value.updatedAt,
        excerpt: value.excerpt,
        category: value.category,
        authorPrincipal: value.authorPrincipal
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentRequestId;
    status: _PaymentStatus;
    expiresAt: bigint;
    userId: Principal;
    ownerPrincipal: string;
    createdAt: bigint;
    subaccount: Uint8Array;
    paymentType: _PaymentType;
    amountE8s: bigint;
}): {
    id: PaymentRequestId;
    status: PaymentStatus;
    expiresAt: bigint;
    userId: Principal;
    ownerPrincipal: string;
    createdAt: bigint;
    subaccount: Uint8Array;
    paymentType: PaymentType;
    amountE8s: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n25(_uploadFile, _downloadFile, value.status),
        expiresAt: value.expiresAt,
        userId: value.userId,
        ownerPrincipal: value.ownerPrincipal,
        createdAt: value.createdAt,
        subaccount: value.subaccount,
        paymentType: from_candid_PaymentType_n27(_uploadFile, _downloadFile, value.paymentType),
        amountE8s: value.amountE8s
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ArticleId;
    title: string;
    content: string;
    isPublished: boolean;
    isPremium: boolean;
    createdAt: _Timestamp;
    tags: Array<string>;
    coverImage: [] | [_ExternalBlob];
    updatedAt: _Timestamp;
    excerpt: string;
    category: string;
    authorPrincipal: _UserId;
}): Promise<{
    id: ArticleId;
    title: string;
    content: string;
    isPublished: boolean;
    isPremium: boolean;
    createdAt: Timestamp;
    tags: Array<string>;
    coverImage?: ExternalBlob;
    updatedAt: Timestamp;
    excerpt: string;
    category: string;
    authorPrincipal: UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        isPublished: value.isPublished,
        isPremium: value.isPremium,
        createdAt: value.createdAt,
        tags: value.tags,
        coverImage: record_opt_to_undefined(await from_candid_opt_n19(_uploadFile, _downloadFile, value.coverImage)),
        updatedAt: value.updatedAt,
        excerpt: value.excerpt,
        category: value.category,
        authorPrincipal: value.authorPrincipal
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    boundPrincipal: [] | [Principal];
    email: string;
    addedAt: _Timestamp;
    intendedRole: _Role;
    boundAt: [] | [_Timestamp];
}): {
    boundPrincipal?: Principal;
    email: string;
    addedAt: Timestamp;
    intendedRole: Role;
    boundAt?: Timestamp;
} {
    return {
        boundPrincipal: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.boundPrincipal)),
        email: value.email,
        addedAt: value.addedAt,
        intendedRole: from_candid_Role_n38(_uploadFile, _downloadFile, value.intendedRole),
        boundAt: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.boundAt))
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logoUrl: [] | [string];
}): {
    logoUrl?: string;
} {
    return {
        logoUrl: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.logoUrl))
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    subscription: [] | [_Subscription];
    isSubscribed: boolean;
    unlockedArticleIds: Array<_ArticleId>;
}): {
    subscription?: Subscription;
    isSubscribed: boolean;
    unlockedArticleIds: Array<ArticleId>;
} {
    return {
        subscription: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.subscription)),
        isSubscribed: value.isSubscribed,
        unlockedArticleIds: value.unlockedArticleIds
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    role: _Role;
}): {
    principal: UserId;
    role: Role;
} {
    return {
        principal: value.principal,
        role: from_candid_Role_n38(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notAuthorized: null;
} | {
    alreadyExists: null;
} | {
    notFound: null;
} | {
    alreadyBound: null;
}): InviteResult {
    return "ok" in value ? InviteResult.ok : "notAuthorized" in value ? InviteResult.notAuthorized : "alreadyExists" in value ? InviteResult.alreadyExists : "notFound" in value ? InviteResult.notFound : "alreadyBound" in value ? InviteResult.alreadyBound : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Consumed: null;
} | {
    Verified: null;
} | {
    Expired: null;
} | {
    Pending: null;
}): PaymentStatus {
    return "Consumed" in value ? PaymentStatus.Consumed : "Verified" in value ? PaymentStatus.Verified : "Expired" in value ? PaymentStatus.Expired : "Pending" in value ? PaymentStatus.Pending : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ArticleUnlock: _ArticleId;
} | {
    Subscription: null;
}): {
    __kind__: "ArticleUnlock";
    ArticleUnlock: ArticleId;
} | {
    __kind__: "Subscription";
    Subscription: null;
} {
    return "ArticleUnlock" in value ? {
        __kind__: "ArticleUnlock",
        ArticleUnlock: value.ArticleUnlock
    } : "Subscription" in value ? {
        __kind__: "Subscription",
        Subscription: value.Subscription
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    editor: null;
} | {
    superadmin: null;
}): Role {
    return "admin" in value ? Role.admin : "editor" in value ? Role.editor : "superadmin" in value ? Role.superadmin : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notAuthorized: null;
}): SettingsResult {
    return "ok" in value ? SettingsResult.ok : "notAuthorized" in value ? SettingsResult.notAuthorized : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notAuthorized: null;
} | {
    alreadyExists: null;
} | {
    notFound: null;
} | {
    notAdmin: null;
}): AdminResult {
    return "ok" in value ? AdminResult.ok : "notAuthorized" in value ? AdminResult.notAuthorized : "alreadyExists" in value ? AdminResult.alreadyExists : "notFound" in value ? AdminResult.notFound : "notAdmin" in value ? AdminResult.notAdmin : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ArticleCard>): Promise<Array<ArticleCard>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ArticleCard_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRequest>): Array<PaymentRequest> {
    return value.map((x)=>from_candid_PaymentRequest_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvitedUser>): Array<InvitedUser> {
    return value.map((x)=>from_candid_InvitedUser_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserRole>): Array<UserRole> {
    return value.map((x)=>from_candid_UserRole_n51(_uploadFile, _downloadFile, x));
}
async function to_candid_ArticleInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleInput): Promise<_ArticleInput> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentType): _PaymentType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SiteSettings_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SiteSettings): _SiteSettings {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    isPremium: boolean;
    tags: Array<string>;
    coverImage?: ExternalBlob;
    excerpt: string;
    category: string;
}): Promise<{
    title: string;
    content: string;
    isPremium: boolean;
    tags: Array<string>;
    coverImage: [] | [_ExternalBlob];
    excerpt: string;
    category: string;
}> {
    return {
        title: value.title,
        content: value.content,
        isPremium: value.isPremium,
        tags: value.tags,
        coverImage: value.coverImage ? candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.coverImage)) : candid_none(),
        excerpt: value.excerpt,
        category: value.category
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logoUrl?: string;
}): {
    logoUrl: [] | [string];
} {
    return {
        logoUrl: value.logoUrl ? candid_some(value.logoUrl) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    editor: null;
} | {
    superadmin: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.editor ? {
        editor: null
    } : value == Role.superadmin ? {
        superadmin: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "ArticleUnlock";
    ArticleUnlock: ArticleId;
} | {
    __kind__: "Subscription";
    Subscription: null;
}): {
    ArticleUnlock: _ArticleId;
} | {
    Subscription: null;
} {
    return value.__kind__ === "ArticleUnlock" ? {
        ArticleUnlock: value.ArticleUnlock
    } : value.__kind__ === "Subscription" ? {
        Subscription: value.Subscription
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
